### PR TITLE
fix: proper schema.org #13

### PR DESCRIPTION
**Pull request by cosmin-serbanescu**

### CODE REVIEW

**Comment by cosmin-serbanescu** [comment]
@selul not sure how to fix that phplint problem

**Comment by selul** [comment]
@cosmin-serbanescu thanks, I will forward this to @abaicus as he in charge of domainwheel reviews

**Review by abaicus — APPROVED** [review]
@cosmin-serbanescu Looks good 👍

**Comment by abaicus** [comment]
@cosmin-serbanescu not sure what is happening here. AFAIK `grunt phplint` is a subtask from the `grunt-theme-fleet` repo - https://github.com/Codeinwp/grunt-theme-fleet/blob/d71c72d9674fd42fa225750827b8d6fd42465c36/grunt/phplint.js. Maybe adding the dependency itself to this repo might work? 

https://www.npmjs.com/package/grunt-phplint

You can test this with `grunt local` as it calls this task too. Also there's no PHPCS.XML file on this repo. Maybe add one?

**Comment by cosmin-serbanescu** [comment]
@abaicus trying to solve this phplint issue, the problem is that this task is added in travis for this repo, checked also the other ones I'm working on (CWP, TI blog) and none of them have it - if I run 'grunt phplint' on them they all fail with the same error. Could I remove it from travis in this case?

**Comment by cosmin-serbanescu** [comment]
@selul it didn't trigger the release, should I add the version thing or maybe there's smth else that needs to be done?

**Comment by selul** [comment]
@cosmin-serbanescu it should be live now, it seems due to the phplint issue the deployment was failing, but I fixed the phplint issue and now works fine.

**Comment by cosmin-serbanescu** [comment]
thanks @selul , working properly!

**Pull request merged**
